version: '3.8'
services:
  attendance_check:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance_check
    networks:
      db_net:
        ipv4_address: 172.20.1.215
    ports:
      - "8000:5000"
networks:
  db_net:
    external:
      name: database_db_net